### ISSUE TITLE
Not working with Collection.upsert

### ISSUE THREAD

**Issue by belokonm** [Meteor-Community-Packages/meteor-collection2#104]
I try to run 
Collection.upsert({_id:id},doc,{validationContext: "newForm"},function(error, result){..});

Server shows error:
Exception while invoking method 'add_book' Error: When the modifier option is true, all validation object keys must be operators. Did you forget `$set`?

**Comment by dr-dimitru** [comment]
@aldeed Same here.
But if is add `$set` operator, I got: `Error: Status is ZERO_RESULTS` error, any help?
