### ISSUE TITLE
Allow client only values

### ISSUE THREAD

**Issue by darkship** [Meteor-Community-Packages/meteor-collection2#266]
I'm trying to do this : https://github.com/darkship/test_localised_schemas.js (with "filter"=true or false)

Could it be possible to get a clientOnly option so that we can insert/update values only on client ?
(This reminds me of https://github.com/aldeed/meteor-collection2/issues/8)

**Comment by aldeed** [comment]
Can you clarify what you mean? What would a call look like that uses `clientOnly` option?

**Comment by darkship** [comment]
I'm not sure if it would actually work or if I see it in the wrong way:

On client, when my collection is synced with the server, every fields will be send to the server. But sometime I want that some fields only exists on the client.
If you try to update a field that is not defined on the server it will be removed by collection2.

Until now, I used <code>new Mongo.Collection(null)</code> and <code>transform</code> to combine a synced collection with an unsynced client only collection.

**Comment by aldeed** [comment]
Interesting idea, but it should be implemented as a separate package. Collection2 now emits an event when a schema is attached, allowing packages to provide additional features for any extra schema options they want.

Here is an example: https://github.com/aldeed/meteor-schema-deny/blob/master/lib/deny.js

So this same structure could be used to add a `clientOnly` option through an add-on package.
