### ISSUE TITLE
IE9/10: Meteor.users.attachSchema - Object doesn't support property or method 'attachSchema'

### ISSUE THREAD

**Issue by ghost** [Meteor-Community-Packages/meteor-collection2#292]
I get the following JavaScript runtime error when running my Meteor app in Internet Explorer 9 and 10 (I haven't checked before 9, and there's no issue in IE11):
        Object doesn't support property or method 'attachSchema'

Problem line: Meteor.users.attachSchema( Schemas.User );

I don't get this error for any of my other Collections that use attachSchema.

I haven't seen this exact issue mentioned anywhere and I've been looking for a while. 

Would really appreciate any help! Thanks!

**Comment by mymedicalshopper** [comment]
I have attached a screenshot of my directory structure, in case it helps. The file in question is located in both/collections/_schemas

![screen shot 2015-12-17 at 5 49 41 pm](https://cloud.githubusercontent.com/assets/6370446/11884337/24d16a04-a4e7-11e5-8fd7-03b7e0ab5698.png)

**Comment by namirsab** [comment]
@aldeed that's also happening to me, only with Meteor.users

**Comment by namirsab** [comment]
Solution: 
`Meteor.users.attachSchema = Meteor.users.attachSchema || Mongo.Collection.prototype.attachSchema`

**Comment by sarita-dc** [comment]
I'm using meteor 1.4 and getting error Cannot set property 'attachSchema' of undefined.
