### ISSUE TITLE
createdAt example in README.md not good for arrays

### ISSUE THREAD

**Issue by rhettlivingston** [Meteor-Community-Packages/meteor-collection2#326]
When used as a field in a subschema for array members, the example given in the readme for "createdAt" doesn't work. Array elements are often "inserted" by using a $push on an update. Since the new entry isn't being created by an insert or upsert, these $push'ed members don't get set and validation fails because the field is required.

A simple change to the createdAt example makes it work. I think that with the change it works in both the normal and array case. It also illustrates something that is probably often necessary when autoValue is used to provide defaults for array elements. Perhaps the README could be updated. I saw bug reports that I believe could have been due to people misunderstanding what is happening in these subdocument cases.

```js
  createdAt: {
    type: Date,
    autoValue: function createdAtAutoValue() {
      if (this.isInsert || (this.isUpdate && this.operator === '$push')) {
        return new Date();
      } else if (this.isUpsert) {
        return { $setOnInsert: new Date() };
      }
      this.unset();  // Prevent user from supplying their own value
    },
  },

```

**Comment by StorytellerCZ** [comment]
@rhettlivingston  I'm not sure I follow. If I'm reading it correctly, then on an update where there is `$push` operator present it would override the `createdAt` value. That doesn't seem to be the desired behavior. Can you provide a sample code of document creation that you have in mind that is not working with the provided sample in readme?
