### ISSUE TITLE
Default Schema for No Matching Selector when using Multiple Schemas

### ISSUE THREAD

**Issue by aldeed** [Meteor-Community-Packages/meteor-collection2#369]
Moved from collection2-core issue https://github.com/aldeed/meteor-collection2-core/issues/43

**Comment by rcsandell** [comment]
Bump. Fixed in #391 https://github.com/aldeed/meteor-collection2/pull/391

**Comment by harryadel** [comment]
Should be good now. Thank you @rcsandell and I apologize for closing the PR. See https://github.com/Meteor-Community-Packages/meteor-collection2/pull/417.
