### ISSUE TITLE
Database model of `meteor-roles` package changed

### ISSUE THREAD

**Issue by SimonSimCity** [Meteor-Community-Packages/meteor-collection2#399]
In version 3 of the `meteor-roles` package I've changed the database model so it doesn't store the assigned roles in the user-document anymore. Since you're here showing an example of a schema that could be used for the `users` collection, I think it's worth mentioning that this only yields for version 1 and 2 of the `meteor-roles` package.

**Comment by harryadelb** [comment]
Done, https://github.com/Meteor-Community-Packages/meteor-collection2/commit/a30bd9895a78b8da742cd37fb6a954ddc14111bb. Thanks for letting us know. :)
