### ISSUE TITLE
[3.0.3] Upsert throws error if query has undefined value

### ISSUE THREAD

**Issue by dovydaskukalis** [Meteor-Community-Packages/meteor-collection2#400]
Code below will throw error `Cannot convert undefined or null to object` because of this line, https://github.com/Meteor-Community-Packages/meteor-collection2/blob/ebc48e2f164e0be73b699a951f48ffef108b2f33/package/collection2/lib.js#L10. 

```
Collection.update(
    {
      key: 'value',
      anotherKey: undefined
    },
    {
      $setOnInsert: {
        createdAt: new Date()
      },
      $set: {
        a: 'b'
      }
    },
    {
      upsert: true
    }
  );

```

**Comment by SimonSimCity** [comment]
Doesn't this yield for everything that is not a string, including `null` and instances of `Date`?

**Comment by dovydaskukalis** [comment]
Only if the value is `undefined` or `null`. Other types such as `Date`, `Number` etc simply return [] which is fine.
