### ISSUE TITLE
Using the all positional operator $[] in nested arrays causes an error

### ISSUE THREAD

**Issue by Shelagh-Lewins** [Meteor-Community-Packages/meteor-collection2#407]
Hi, I don't know if this is a bug in simple schema or if I'm doing something wrong.

I have a nested array like this:

```
myGrid = [
[1,0,2,3],
[2,2,0,1].
]
```

My schema is like this:

```
const MyCollectionSchema = new SimpleSchema({
'myGrid': {
	'type': Array,
},
'myGrid.$': {
	'type': Array,
},
'myGrid.$.$': {
	'type': SimpleSchema.Integer,
},
});
```
And I am updating the array like this:

```
const update = {};
update.$push = {
	'myGrid.$[]': {
		'$each': [3,2,3],
		'$position': 2,
	},
};

MyCollection.update({ _id }, update);
```

This inserts the new values [3,2,3] into each child array at position 2, as per the[ docs](https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/#position-nested-arrays-filtered).
(I'm using this form because I'm performing multiple updates in one operation, but I've left out the other updates from this example.)

When I run the code I see this error:

`Exception ...{ Error: myGrid.$[] is not allowed by the schema (myGrid.$[])`

If I bypass Collection2 like this, the operation succeeds:

`MyCollection.update({ _id }, update, { 'bypassCollection2': true });`

Is there a way to make this operation pass the schema? Or is it a bug? Thank you.

**Comment by harryadelb** [comment]
Again, it's related to simple-schema. There's a way to make it passable which is to remove the `[]` in `myGrid.$[]`.

The error happens [here](https://github.com/aldeed/simple-schema-js/blob/54929ab1b12e3fbdb7ffc7a5647df447fd9e5bd7/package/lib/doValidation.js#L42).

I'm wondering though how can you use the positional operator when you're coupling it with position and each?? According to the [documentation](https://docs.mongodb.com/manual/reference/operator/update/positional-all/) using positional operator set the value for all values.

```
db.collection.update(
   { myArray: [ 5, 8 ] },
   { $set: { "myArray.$[]": 10 } },
   { upsert: true }
)
```
So what's the use for $each and $position in your example here?

**Comment by StorytellerCZ** [comment]
Since this is primarily an issue with simpl-schema I'm going to close this issue. If you feel that it is something that we can deal with here or the situation changes, please re-open this issue.

**Comment by harryadel** [comment]
While I've read too deep into it but this [PR](https://github.com/longshotlabs/simpl-schema/pull/442) may alleviate the problem you're facing guys.

**Comment by derwaldgeist** [comment]
Just came across this problem. Being able to adress multiple array items is actually quite important. Has this been fixed in `simpl-schema` in the meantime?
