### ISSUE TITLE
relplace lodash with underscore

### ISSUE THREAD

**Issue by jirikrepl** [Meteor-Community-Packages/meteor-collection2#429]
I see that collection2 has some dependencies on lodash.
collection2.js uses lodash only in a few places.
I saw that those lodash calls should be compatible with underscore

I could create a PR with something similar to this commit:
https://github.com/jirikrepl/meteor-collection2/commit/3f2046bf6ffdc3b02b899bc6fd89131beaf1af7f

In my app, many other packages depend on underscore.
I think that meteor packages use underscore more.

Lodash in collection2 adds another 6Kb into the bundle.

What do you think?
@harryadel @StorytellerCZ

**Comment by copleykj** [comment]
If possible I think it would be better to examine usage and replace with functionally equivalent internal code.

**Comment by StorytellerCZ** [comment]
I'm all for replacing external dependencies, but more along @copleykj comment.

**Comment by harryadel** [comment]
I'd say this is a no go. Meteor is on its way to remove underscore as many of the utilities offered by underscore can be swapped with [native implementations](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore). And in our case of Collection2 we're only [importing](https://github.com/Meteor-Community-Packages/meteor-collection2/blob/master/package/collection2/package.js#L11) the functions we need import the whole package; only what we need. So, we're not necessarily bloating up the library. Relying on underscore is a bad investment and not future proof given the climate. 

What'd I be interested in is replacing [those lodash utilities](https://github.com/Meteor-Community-Packages/meteor-collection2/blob/master/package/collection2/package.js#L11)) with native functions. If you can open up a PR about that I'll gladly accept it.

https://github.com/meteor/meteor-feature-requests/issues/48#issuecomment-634533727
https://github.com/meteor/meteor/pull/11531
https://github.com/meteor/meteor/pull/11495
https://github.com/meteor/blaze/pull/331
