### ISSUE TITLE
4.0 load function is not dynamic

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/meteor-collection2#446]
In `dynamic.js` the load function is actually  no real dynamic import

Actual: a nested import

```js
Collection2.load = function () {
    import './main';
}
```

Expected:  a dynamic import

```js
Collection2.load = async function () {
    await import('./main')
}
```

**Comment by harryadel** [comment]
Thanks for pointing that out, start and merge. I think you've maintainers rights here. If not start a PR and I'll merge it.
