### ISSUE TITLE
Insert with 'bypassCollection2: true' throws an exception

### ISSUE THREAD

**Issue by pmogollons** [Meteor-Community-Packages/meteor-collection2#448]
When inserting a document with options, like to bypassCollection2 it throws an exception.

collection.insertAsync(doc, {bypassCollection2: true})

Exception in Mongo write: TypeError: object is not a function
  at packages/mongo/mongo_driver.js:322:1
  at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)

**To Reproduce**

1. use insertAsync with an options object
2. You get the error

**Expected behavior**

insertAsync should accept a 2nd param with options

**Additional context**

This is related to #290. This was fixed in [91c6462](https://github.com/Meteor-Community-Packages/meteor-collection2/commit/91c6462123b1f01c57952ff1c1548081cec73d74), but only for .insert method as async methods were not a thing at that time.

**Comment by harryadel** [comment]
Can you give the new version `4.0.2-beta.1` a try?

**Comment by jankapunkt** [comment]
Should be fixed in `4.0.2`

**Comment by harryadel** [comment]
Should this problem persist, let us know. Thanks!
