### ISSUE TITLE
On-the-Fly Conversions

### ISSUE THREAD

**Issue by aldeed** [Meteor-Community-Packages/meteor-collection2#45]
I have a rough idea of a way to handle on-the-fly conversions.
1. Add `convert` option to schema, false by default.
2. Override the `find` method. If `convert: true` and `autoValue` is set, call an asynchronous `update` for all of the documents that `find` is returning, right before they are returned.
3. For each update, get the complete current doc, pass that to `autoValue` for each field needing conversion, then do $set for that field with the returned auto value.

The idea is that most schema changes don't require large scale data conversions. Instead, each document can be converted the first time it is requested. Since we'd do the conversion updates asynchronously, it wouldn't affect `find` performance all that much. Unconverted documents would be used temporarily until the conversion completes, causing deps update.

One key would be to be able to track when the conversion has run for a doc. This likely requires creating an indexed tracking collection to be used internally by C2. This would do two things: prevent running the conversion more than once per doc, and allow the user to see when a conversion has been run on all docs, meaning that any code handling the old schema can be removed. To do this accurately, we might also need a `version` option, or maybe `convert` can be set to a version identifier instead of `true`.

Anyone with thoughts, feel free to comment.

**Comment by comerc** [comment]
[Do you know about it?](http://docs.meteor.com/#/full/mongo_collection)

transform Function
An optional transformation function. Documents will be passed through this function before being returned from fetch or findOne, and before being passed to callbacks of observe, map, forEach, allow, and deny. Transforms are not applied for the callbacks of observeChanges or to cursors returned from publish functions.

**Comment by Floriferous** [comment]
I find myself needing this, as we're writing a lot of unnecessary migrations to add defaultValues, autoValues etc on production data very often.

The important part is to not update some autoValues (like `updatedAt` for example).

I guess a simple function like this should do the job, just call it from a method somewhere (requires `dburles:mongo-collection-instances`):

```js
import { Mongo } from 'meteor/mongo';

import omit from 'lodash/omit';

const skippedCollections = ['_cacheMigrations', 'grapher_counts']; // Any collections you want to skip
const skippedFields = ['_id', 'createdAt', 'updatedAt']; // Any fields you want to skip

const makeCleanDocument = (collection, schema) => (document) => {
  const { _id } = document;
  const cleanDoc = schema.clean(document, {
    mutate: true,
    filter: true,
    autoConvert: true,
    removeEmptyStrings: false,
    trimStrings: true,
    getAutoValues: true,
  });

  const withoutSkippedFields = omit(cleanDoc, skippedFields);

  return collection
    .rawCollection()
    .update({ _id }, { $set: withoutSkippedFields });
};

const cleanCollection = (collection) => {
  if (!collection.name || skippedCollections.includes(collection.name)) {
    return;
  }

  const schema = collection.instance._c2._simpleSchema;
  const allDocuments = collection.instance.find({}).fetch();

  return Promise.all(allDocuments.map(makeCleanDocument(collection, schema)));
};

export const cleanAllData = async () => {
  const collections = Mongo.Collection.getAll();

  await Promise.all(collections.map(cleanCollection));
};
```
