### ISSUE TITLE
client side update impossible | server side works fine

### ISSUE THREAD

**Issue by leroadrunner** [Meteor-Community-Packages/meteor-collection2#53]
I have this collection2 :

Items             = new Meteor.Collection2("items",{
  schema: {
    name:                 { type: String, max: 60 },
    mainDirectory:        { type: String, max: 65, unique: true },
    mainPageThumbnail:    { type: [Object]},
    mainPageBackground:   { type: [Object]},
    category:             { type: String },
    cssStyle:             { type: String },
    inGridSize:           { type: String },
    mainRank:             { type: Number, max: 999 },
    itemSubCategories:    { type: [Object] },  
    'itemSubCategories.$.name':                   { type: String },
    'itemSubCategories.$.text1':                  { type: String, max: 5000 },
    'itemSubCategories.$.text2':                  { type: String, max: 5000 },  
    'itemSubCategories.$.video':                  { type: String, regEx: SchemaRegEx.Url, max: 500 },
    'itemSubCategories.$.songs':                  { type: [Object] },
    'itemSubCategories.$.pictures':               { type: [Object] }, 
    'itemSubCategories.$.testimonialsPictures':   { type: [Object] }
  }
}); 

when I try update itemSubCategories.$.pictures 
var modifier                = {$set: {}};
modifier.$set[ "itemSubCategories." + activeItemSubCategories + ".pictures" ] = {name: "picture1.jpg", position: '1'},{name: "picture2.jpg", position: '2'}  ;

I have this message :
Uncaught Error: When the modifier option is true, validation object must have at least one operator

I try lot of variations, always the same result.
All my others updates on client side work well.
As workaround, I go do my update server side, with the exact same syntax.

**Comment by aramk** [comment]
Using this code gave me the following error:
```
Entities.update(entityId, {$set: {}});
```

> Error: When the modifier option is true, validation object must have at least one operator

Changing it to prevent validation prevented the error:
```
Entities.update(entityId, {$set: {}}, {validate: false});
```

**Comment by eminaz** [comment]
@aldeed if I have [Object] or [String] as the type, how do I explicitly define the allowed properties for that object?

**Comment by Firfi** [comment]
@eminaz would answer for @aldeed here: `yourArray.$.yourProperty` - see docs for examples

**Comment by assutech** [comment]
Is there anyway I can set type to Object and just pass any object without defining properties for that object? In case for instance where the keys are dynamic.

**Comment by aldeed** [comment]
@assutech Add `blackbox: true` to the `Object` field in the schema.

**Comment by assutech** [comment]
Worked like a cham, thanks. :)
