### ISSUE TITLE
AutoValue on object inside array causes mongoError

### ISSUE THREAD

**Issue by czeslaaw** [Meteor-Community-Packages/meteor-collection2#67]
When I have schema like this:

```
'comments.$.author': {
            type: String,
            autoValue: function() {
                    return this.userId;
            }
        }
```

Then on update it becames something like this in mongo:

```
{ '$push': { comments: {} },
  '$set': { 'comments.0.author': 'Qp4KFYjFCXPfDZJ8q' } }
```

This throws a MongoError: have conflicting mods in update.

**Comment by enzoglauber** [comment]
I've tried something similar, only just with the object and does't run autoValue:
	status: {
		type: Object,
		label: "status",
		optional: true
	},
		"status._id": {
			type: String,
			label:"Status ID",
			optional: true
		},
		"status.at": {
			type: Date,
			autoValue: function() {
				if (this.isInsert) {
					return new Date();
				} else if (this.isUpsert) {
					return {$setOnInsert: new Date()};
				} else {
					this.unset();
				}
    		}
	}


:´(
