### ISSUE TITLE
No validation message for Autoform unique field

### ISSUE THREAD

**Issue by SantoshSrinivas79** [Meteor-Community-Packages/meteor-collection2#79]
I set a field to `unique` true and `index` true in my Collection2 object. The validation happens correctly when I enter a duplicate value as referenced in #75 

However there is no validation message that is showing up in my autoform below the field.

However, in the console on the client, I can see the Meteor error that gets thrown.

Please advise on the following two questions:
1. How to add an error message when the unique check fails for a particular field
2. How to override the error message in my collection2 definition.

Edit: It looks like `invalidKeys` are not getting added for `notUnique`. However, you referenced this in  [CHANGELOG.md#0310](https://github.com/aldeed/meteor-collection2/blob/master/CHANGELOG.md#0310).

Please advise.

**Comment by Pushplaybang** [comment]
Hey There!

I'm not using autoForm, just collection2 and can't seem to get an error message for unique back on the client, (I am getting all other validation messages), in fact my initial check for `if (!error)` passes in the Meteor.call callback, but the `Topic Title must be unique` message is only logged on the server and never sent to the client it seems.  I can guess why Meteor.call's callback returns successfully on the client but don't have a clue why I'm not getting anything back for the unique check.

**Comment by outluch** [comment]
+1 would be awesome to have uniqueness failure messages on client.
