### ISSUE TITLE
update to 0.4.0 - E11000 duplicate key error index

### ISSUE THREAD

**Issue by picsoung** [Meteor-Community-Packages/meteor-collection2#80]
After updating collection to the latest package I got a `E11000 duplicate key error index: meteor.Books.$c2_url  dup key: { : "http://mydomain.com" }`

I added `index` to my collection with no effect... :( 

```
url: {
            type: String,
            label: "url",
            index: 1,
            unique: true,
            regEx: SimpleSchema.RegEx.Url,
        },
```

setting up index to `true` does not help either.
Thanks again and sorry for the whole trouble,
Best

**Comment by aj07mm** [comment]
Use 
```
meteor reset
```
 it worked for me
